--SQL SERVER
GO CREATE TABLE [dbo].[elements](
		[id] [int] NOT NULL IDENTITY(1, 1),
		[code] [varchar](max) NOT NULL,
		[property] [varchar](max) NOT NULL,
		[propertySymbol] [varchar](6) NOT NULL,
		[propertySecond] [varchar](max) NULL,
		[propertySecondSymbol] [varchar](6) NULL,
		[propertiesOperation] [varchar](1) NULL,
		[propertyUnit] [varchar](10) NOT NULL,
		[rangeFrom] [decimal] NULL,
		[rangeTo] [decimal] NULL,
		[rangeUnit] [varchar](10) NOT NULL,
		[rangeProperty] [varchar](max) NOT NULL,
		[rangePropertySymbol] [varchar](6) NOT NULL,
		[toleranceStart] [decimal] NULL,
		[toleranceEnd] [decimal] NULL,
		[toleranceUnit] [varchar](10) NOT NULL,
		[toleranceProperty] [varchar](max) NULL,
		[tolerancePropertySymbol] [varchar](6) NULL,
		[illustration] [varchar](max) NULL,
		[toleranceStartAgreement] [decimal] NULL,
		[toleranceEndAgreement] [decimal] NULL,
		[name] [varchar](max) NOT NULL,
		CONSTRAINT [idIndex] UNIQUE NONCLUSTERED ([id] ASC) WITH (
			PAD_INDEX = OFF,
			STATISTICS_NORECOMPUTE = OFF,
			IGNORE_DUP_KEY = OFF,
			ALLOW_ROW_LOCKS = ON,
			ALLOW_PAGE_LOCKS = ON,
			OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
		) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO --MYSQL
	CREATE TABLE elements(
		id int NOT NULL AUTO_INCREMENT,
		code varchar(255) NOT NULL,
		property varchar(255) NOT NULL,
		propertySymbol varchar(6) NOT NULL,
		propertySecond varchar(255) NULL,
		propertySecondSymbol varchar(6) NULL,
		propertiesOperation varchar(255) NULL,
		propertyUnit varchar(10) NOT NULL,
		rangeFrom DECIMAL(19, 4) NULL,
		rangeTo DECIMAL(19, 4) NULL,
		rangeUnit varchar(10) NOT NULL,
		rangeProperty varchar(255) NOT NULL,
		rangePropertySymbol varchar(6) NOT NULL,
		toleranceStart DECIMAL(19, 4) NULL,
		toleranceEnd DECIMAL(19, 4) NULL,
		toleranceUnit varchar(10) NOT NULL,
		toleranceProperty varchar(255) NULL,
		tolerancePropertySymbol varchar(6) NULL,
		illustration varchar(255) NULL,
		toleranceStartAgreement DECIMAL(19, 4) NULL,
		toleranceEndAgreement DECIMAL(19, 4) NULL,
		name varchar(255) NOT NULL,
		PRIMARY KEY(id)
	) --POSTGRESQL
	CREATE TABLE elements(
		id SERIAL,
		code varchar(255) NOT NULL,
		property varchar(255) NOT NULL,
		propertySymbol varchar(6) NOT NULL,
		propertySecond varchar(255) NULL,
		propertySecondSymbol varchar(6) NULL,
		propertiesOperation varchar(255) NULL,
		propertyUnit varchar(10) NOT NULL,
		rangeFrom DECIMAL(19, 4) NULL,
		rangeTo DECIMAL(19, 4) NULL,
		rangeUnit varchar(10) NOT NULL,
		rangeProperty varchar(255) NOT NULL,
		rangePropertySymbol varchar(6) NOT NULL,
		toleranceStart DECIMAL(19, 4) NULL,
		toleranceEnd DECIMAL(19, 4) NULL,
		toleranceUnit varchar(10) NOT NULL,
		toleranceProperty varchar(255) NULL,
		tolerancePropertySymbol varchar(6) NULL,
		illustration varchar(255) NULL,
		toleranceStartAgreement DECIMAL(19, 4) NULL,
		toleranceEndAgreement DECIMAL(19, 4) NULL,
		name varchar(255) NOT NULL,
		PRIMARY KEY(id)
	)