export const MockData = [
	{
		code: "PN-EN 10024",
		name: "DWUTEOWNIKI STALOWE Z POCHYLONĄ WEWNĘTRZNĄ POWIERZCHNIĄ STOPEK WALCOWANE NA GORĄCO",
		properties: [
			{
				property: "prostość",
				propertySymbol: "qyy",
				propertyUnit: "mm",
				propertySecond: "prostość",
				propertySecondSymbol: "qxx",
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "L",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 80,
						rangeTo: 180,
						toleranceStart: 0,
						toleranceEnd: 0.3,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "L",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 180,
						rangeTo: 360,
						toleranceStart: 0,
						toleranceEnd: 0.15,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "L",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 360,
						rangeTo: 0,
						toleranceStart: 0,
						toleranceEnd: 0.1,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "wysokość",
				propertySymbol: "h",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "wysokość",
						tolerancePropertySymbol: "h",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 200,
						toleranceStart: 2,
						toleranceEnd: 2,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "wysokość",
						tolerancePropertySymbol: "h",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 200,
						rangeTo: 400,
						toleranceStart: 3,
						toleranceEnd: 3,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "wysokość",
						tolerancePropertySymbol: "h",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 400,
						rangeTo: 0,
						toleranceStart: 4,
						toleranceEnd: 4,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "szerokość stopki",
				propertySymbol: "b",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość stopki",
						rangePropertySymbol: "b",
						toleranceProperty: "szerokość stopki",
						tolerancePropertySymbol: "b",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 75,
						toleranceStart: 1.5,
						toleranceEnd: 1.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość stopki",
						rangePropertySymbol: "b",
						toleranceProperty: "szerokość stopki",
						tolerancePropertySymbol: "b",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 75,
						rangeTo: 100,
						toleranceStart: 2,
						toleranceEnd: 2,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość stopki",
						rangePropertySymbol: "b",
						toleranceProperty: "szerokość stopki",
						tolerancePropertySymbol: "b",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 100,
						rangeTo: 125,
						toleranceStart: 2.5,
						toleranceEnd: 2.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość stopki",
						rangePropertySymbol: "b",
						toleranceProperty: "szerokość stopki",
						tolerancePropertySymbol: "b",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 125,
						rangeTo: 0,
						toleranceStart: 3,
						toleranceEnd: 3,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "grubość stopki",
				propertySymbol: "t",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "grubość stopki",
						rangePropertySymbol: "t",
						toleranceProperty: "grubość stopki",
						tolerancePropertySymbol: "t",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 7,
						toleranceStart: 0.5,
						toleranceEnd: 1.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "grubość stopki",
						rangePropertySymbol: "t",
						toleranceProperty: "grubość stopki",
						tolerancePropertySymbol: "t",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 7,
						rangeTo: 10,
						toleranceStart: 1,
						toleranceEnd: 2,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "grubość stopki",
						rangePropertySymbol: "t",
						toleranceProperty: "grubość stopki",
						tolerancePropertySymbol: "t",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 10,
						rangeTo: 20,
						toleranceStart: 1.5,
						toleranceEnd: 2.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "grubość stopki",
						rangePropertySymbol: "t",
						toleranceProperty: "grubość stopki",
						tolerancePropertySymbol: "t",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 20,
						rangeTo: 0,
						toleranceStart: 2,
						toleranceEnd: 2.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "grubość środnika",
				propertySymbol: "s",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "grubość środnika",
						rangePropertySymbol: "s",
						toleranceProperty: "grubość środnika",
						tolerancePropertySymbol: "s",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 7,
						toleranceStart: 1,
						toleranceEnd: 0.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "grubość środnika",
						rangePropertySymbol: "s",
						toleranceProperty: "grubość środnika",
						tolerancePropertySymbol: "s",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 7,
						rangeTo: 10,
						toleranceStart: 1.5,
						toleranceEnd: 0.7,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "grubość środnika",
						rangePropertySymbol: "s",
						toleranceProperty: "grubość środnika",
						tolerancePropertySymbol: "s",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 10,
						rangeTo: 0,
						toleranceStart: 2,
						toleranceEnd: 1,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "skośność stopek",
				propertySymbol: "k",
				propertyUnit: "mm",
				propertySecond: "skośność stopek",
				propertySecondSymbol: "k`",
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość stopki",
						rangePropertySymbol: "b",
						toleranceProperty: "szerokość stopki",
						tolerancePropertySymbol: "b",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 100,
						toleranceStart: 0,
						toleranceEnd: 2,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "%",
						rangeProperty: "szerokość stopki",
						rangePropertySymbol: "b",
						toleranceProperty: "szerokość stopki",
						tolerancePropertySymbol: "b",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 100,
						rangeTo: 0,
						toleranceStart: 0,
						toleranceEnd: 2,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "niesymetryczność stopek",
				propertySymbol: "e",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość stopki",
						rangePropertySymbol: "b",
						toleranceProperty: "niesymetryczność stopek",
						tolerancePropertySymbol: "e",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 100,
						toleranceStart: 0,
						toleranceEnd: 2,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość stopki",
						rangePropertySymbol: "b",
						toleranceProperty: "niesymetryczność stopek",
						tolerancePropertySymbol: "e",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 100,
						rangeTo: 0,
						toleranceStart: 0,
						toleranceEnd: 3,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "masa",
				propertySymbol: "m",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "masa",
						rangePropertySymbol: "m",
						toleranceProperty: "masa",
						tolerancePropertySymbol: "m",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 0,
						toleranceStart: 4,
						toleranceEnd: 4,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "długość",
				propertySymbol: "L",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "długość",
						rangePropertySymbol: "L",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "L",
						toleranceUnit: "mm",
						canAgreeTolerance: true,
						rangeFrom: 0,
						rangeTo: 0,
						toleranceStart: 50,
						toleranceEnd: 50,
						toleranceStartAgreement: 50,
						toleranceEndAgreement: 100,
					},
				],
			},
		],
		allNeededValues: [
			{
				name: "wysokość",
				symbol: "h",
				unit: "mm",
			},
			{
				name: "prostość",
				symbol: "qyy",
				unit: "mm",
			},
			{
				name: "prostość",
				symbol: "qxx",
				unit: "mm",
			},
			{
				name: "szerokość stopki",
				symbol: "b",
				unit: "mm",
			},
			{
				name: "grubość stopki",
				symbol: "t",
				unit: "mm",
			},
			{
				name: "grubość środnika",
				symbol: "s",
				unit: "mm",
			},
			{
				name: "skośność stopek",
				symbol: "k",
				unit: "mm",
			},
			{
				name: "skośność stopek",
				symbol: "k`",
				unit: "mm",
			},
			{
				name: "niesymetryczność stopek",
				symbol: "e",
				unit: "mm",
			},
			{
				name: "masa",
				symbol: "m",
				unit: "mm",
			},
			{
				name: "długość",
				symbol: "L",
				unit: "mm",
			},
		],
	},
	{
		code: "PN-EN 10056-2",
		name: "kątowniki równoramienne i nierównoramenne z stali konstrukcyjnej",
		properties: [
			{
				property: "długość ramienia",
				propertySymbol: "a",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "długość",
						rangePropertySymbol: "a",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "a",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 50,
						toleranceStart: 1,
						toleranceEnd: 1,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "długość",
						rangePropertySymbol: "a",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "a",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 50,
						rangeTo: 100,
						toleranceStart: 2,
						toleranceEnd: 2,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "długość",
						rangePropertySymbol: "a",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "a",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 100,
						rangeTo: 150,
						toleranceStart: 3,
						toleranceEnd: 3,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "długość",
						rangePropertySymbol: "a",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "a",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 150,
						rangeTo: 200,
						toleranceStart: 4,
						toleranceEnd: 4,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "długość",
						rangePropertySymbol: "a",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "a",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 200,
						rangeTo: 0,
						toleranceStart: 4,
						toleranceEnd: 6,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "grubość ramienia",
				propertySymbol: "t",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "grubość",
						rangePropertySymbol: "t",
						toleranceProperty: "grubość",
						tolerancePropertySymbol: "t",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 5,
						toleranceStart: 0.5,
						toleranceEnd: 0.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "grubość",
						rangePropertySymbol: "t",
						toleranceProperty: "grubość",
						tolerancePropertySymbol: "t",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 5,
						rangeTo: 10,
						toleranceStart: 0.75,
						toleranceEnd: 0.75,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "grubość",
						rangePropertySymbol: "t",
						toleranceProperty: "grubość",
						tolerancePropertySymbol: "t",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 10,
						rangeTo: 15,
						toleranceStart: 1,
						toleranceEnd: 1,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "grubość",
						rangePropertySymbol: "t",
						toleranceProperty: "grubość",
						tolerancePropertySymbol: "t",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 15,
						rangeTo: 0,
						toleranceStart: 1.2,
						toleranceEnd: 1.2,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "skośność",
				propertySymbol: "k",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "długość ramienia",
						rangePropertySymbol: "a",
						toleranceProperty: "skośność",
						tolerancePropertySymbol: "k",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 100,
						toleranceStart: 0,
						toleranceEnd: 1,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "długość ramienia",
						rangePropertySymbol: "a",
						toleranceProperty: "skośność",
						tolerancePropertySymbol: "k",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 100,
						rangeTo: 150,
						toleranceStart: 0,
						toleranceEnd: 1.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "długość ramienia",
						rangePropertySymbol: "a",
						toleranceProperty: "skośność",
						tolerancePropertySymbol: "k",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 150,
						rangeTo: 200,
						toleranceStart: 0,
						toleranceEnd: 2,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "długość ramienia",
						rangePropertySymbol: "a",
						toleranceProperty: "skośność",
						tolerancePropertySymbol: "k",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 200,
						rangeTo: 0,
						toleranceStart: 0,
						toleranceEnd: 3,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "prostość (całość)",
				propertySymbol: "q",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "długość ramienia",
						rangePropertySymbol: "a",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "L",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 150,
						toleranceStart: 0,
						toleranceEnd: 0.4,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "długość ramienia",
						rangePropertySymbol: "a",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "L",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 150,
						rangeTo: 200,
						toleranceStart: 0,
						toleranceEnd: 0.2,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "długość ramienia",
						rangePropertySymbol: "a",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "L",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 200,
						rangeTo: 0,
						toleranceStart: 0,
						toleranceEnd: 0.1,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "prostość (część)",
				propertySymbol: "q",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "długość pomiarowa",
						rangePropertySymbol: "dp",
						toleranceProperty: "prostość",
						tolerancePropertySymbol: "q",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 1500,
						rangeTo: 1500,
						toleranceStart: 0,
						toleranceEnd: 6,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "długość pomiarowa",
						rangePropertySymbol: "dp",
						toleranceProperty: "prostość",
						tolerancePropertySymbol: "q",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 2000,
						rangeTo: 2000,
						toleranceStart: 0,
						toleranceEnd: 3,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "długość pomiarowa",
						rangePropertySymbol: "dp",
						toleranceProperty: "prostość",
						tolerancePropertySymbol: "q",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 3000,
						rangeTo: 3000,
						toleranceStart: 0,
						toleranceEnd: 3,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
		],
		allNeededValues: [
			{
				name: "długość",
				symbol: "a",
				unit: "mm",
			},
			{
				name: "długość ramienia",
				symbol: "a",
				unit: "mm",
			},
			{
				name: "grubość",
				symbol: "t",
				unit: "mm",
			},
			{
				name: "grubość ramienia",
				symbol: "t",
				unit: "mm",
			},
			{
				name: "skośność",
				symbol: "k",
				unit: "mm",
			},
			{
				name: "prostość (całość)",
				symbol: "q",
				unit: "mm",
			},
			{
				name: "długość pomiarowa",
				symbol: "dp",
				unit: "mm",
			},
			{
				name: "prostość (część)",
				symbol: "q",
				unit: "mm",
			},
		],
	},
	{
		code: "PN-EN 10058",
		name: "PRĘTY STALOWE PŁASKIE WALCOWANE NA GORĄCO OGÓLNEGO ZASTOSOWANIA",
		properties: [
			{
				property: "szerokość",
				propertySymbol: "b",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość",
						rangePropertySymbol: "b",
						toleranceProperty: "szerokość",
						tolerancePropertySymbol: "b",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 10,
						rangeTo: 40,
						toleranceStart: 0.75,
						toleranceEnd: 0.75,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość",
						rangePropertySymbol: "b",
						toleranceProperty: "szerokość",
						tolerancePropertySymbol: "b",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 40,
						rangeTo: 80,
						toleranceStart: 1,
						toleranceEnd: 1,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość",
						rangePropertySymbol: "b",
						toleranceProperty: "szerokość",
						tolerancePropertySymbol: "b",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 80,
						rangeTo: 100,
						toleranceStart: 1.5,
						toleranceEnd: 1.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość",
						rangePropertySymbol: "b",
						toleranceProperty: "szerokość",
						tolerancePropertySymbol: "b",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 100,
						rangeTo: 120,
						toleranceStart: 2,
						toleranceEnd: 2,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość",
						rangePropertySymbol: "b",
						toleranceProperty: "szerokość",
						tolerancePropertySymbol: "b",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 120,
						rangeTo: 150,
						toleranceStart: 2.5,
						toleranceEnd: 2.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "grubość",
				propertySymbol: "t",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "grubość",
						rangePropertySymbol: "t",
						toleranceProperty: "grubość",
						tolerancePropertySymbol: "t",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 20,
						toleranceStart: 0.5,
						toleranceEnd: 0.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "grubość",
						rangePropertySymbol: "t",
						toleranceProperty: "grubość",
						tolerancePropertySymbol: "t",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 20,
						rangeTo: 40,
						toleranceStart: 1,
						toleranceEnd: 1,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "grubość",
						rangePropertySymbol: "t",
						toleranceProperty: "grubość",
						tolerancePropertySymbol: "t",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 40,
						rangeTo: 80,
						toleranceStart: 1.5,
						toleranceEnd: 1.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "prostość",
				propertySymbol: "q",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "przekrój poprzeczny",
						rangePropertySymbol: "pp",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "l",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 1000,
						toleranceStart: 0,
						toleranceEnd: 0.4,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "przekrój poprzeczny",
						rangePropertySymbol: "pp",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "l",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 1000,
						rangeTo: 0,
						toleranceStart: 0,
						toleranceEnd: 0.25,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "skośność",
				propertySymbol: "u",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "grubość",
						rangePropertySymbol: "t",
						toleranceProperty: "skośność",
						tolerancePropertySymbol: "u",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 10,
						rangeTo: 25,
						toleranceStart: 0,
						toleranceEnd: 0.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "grubość",
						rangePropertySymbol: "t",
						toleranceProperty: "skośność",
						tolerancePropertySymbol: "u",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 25,
						rangeTo: 40,
						toleranceStart: 0,
						toleranceEnd: 1,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "grubość",
						rangePropertySymbol: "t",
						toleranceProperty: "skośność",
						tolerancePropertySymbol: "u",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 40,
						rangeTo: 80,
						toleranceStart: 0,
						toleranceEnd: 1.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
		],
		allNeededValues: [
			{
				name: "szerokość",
				symbol: "b",
				unit: "mm",
			},
			{
				name: "grubość",
				symbol: "t",
				unit: "mm",
			},
			{
				name: "przekrój poprzeczny",
				symbol: "pp",
				unit: "mm",
			},
			{
				name: "prostość",
				symbol: "q",
				unit: "mm",
			},
			{
				name: "skośność",
				symbol: "u",
				unit: "mm",
			},
		],
	},
	{
		code: "PN-EN 10279",
		name: "CEOWNIKI STALOWE WALCOWANE NA GORĄCO",
		properties: [
			{
				property: "wysokość",
				propertySymbol: "h",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "wysokość",
						tolerancePropertySymbol: "h",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 65,
						toleranceStart: 1.5,
						toleranceEnd: 1.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "wysokość",
						tolerancePropertySymbol: "h",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 65,
						rangeTo: 200,
						toleranceStart: 2,
						toleranceEnd: 2,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "wysokość",
						tolerancePropertySymbol: "h",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 200,
						rangeTo: 400,
						toleranceStart: 3,
						toleranceEnd: 3,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "wysokość",
						tolerancePropertySymbol: "h",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 400,
						rangeTo: 0,
						toleranceStart: 4,
						toleranceEnd: 4,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "szerokość stopki",
				propertySymbol: "b",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość stopki",
						rangePropertySymbol: "b",
						toleranceProperty: "szerokość stopki",
						tolerancePropertySymbol: "b",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 50,
						toleranceStart: 1.5,
						toleranceEnd: 1.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość stopki",
						rangePropertySymbol: "b",
						toleranceProperty: "szerokość stopki",
						tolerancePropertySymbol: "b",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 50,
						rangeTo: 100,
						toleranceStart: 2,
						toleranceEnd: 2,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość stopki",
						rangePropertySymbol: "b",
						toleranceProperty: "szerokość stopki",
						tolerancePropertySymbol: "b",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 100,
						rangeTo: 125,
						toleranceStart: 2.5,
						toleranceEnd: 2.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość stopki",
						rangePropertySymbol: "b",
						toleranceProperty: "szerokość stopki",
						tolerancePropertySymbol: "b",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 125,
						rangeTo: 0,
						toleranceStart: 3,
						toleranceEnd: 3,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "grubość środnika",
				propertySymbol: "s",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "grubość środnika",
						rangePropertySymbol: "s",
						toleranceProperty: "grubość środnika",
						tolerancePropertySymbol: "s",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 10,
						toleranceStart: 0.5,
						toleranceEnd: 0.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "grubość środnika",
						rangePropertySymbol: "s",
						toleranceProperty: "grubość środnika",
						tolerancePropertySymbol: "s",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 10,
						rangeTo: 15,
						toleranceStart: 0.7,
						toleranceEnd: 0.7,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "grubość środnika",
						rangePropertySymbol: "s",
						toleranceProperty: "grubość środnika",
						tolerancePropertySymbol: "s",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 15,
						rangeTo: 0,
						toleranceStart: 1,
						toleranceEnd: 1,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "grubość stopki",
				propertySymbol: "t",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "grubość stopki",
						rangePropertySymbol: "t",
						toleranceProperty: "grubość stopki",
						tolerancePropertySymbol: "t",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 10,
						toleranceStart: 0.5,
						toleranceEnd: 0,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "grubość stopki",
						rangePropertySymbol: "t",
						toleranceProperty: "grubość stopki",
						tolerancePropertySymbol: "t",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 10,
						rangeTo: 15,
						toleranceStart: 1,
						toleranceEnd: 0,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "grubość stopki",
						rangePropertySymbol: "t",
						toleranceProperty: "grubość stopki",
						tolerancePropertySymbol: "t",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 15,
						rangeTo: 0,
						toleranceStart: 1.5,
						toleranceEnd: 0,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "promień naroża",
				propertySymbol: "r3",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "promień naroża",
						rangePropertySymbol: "r3",
						toleranceProperty: "grubość stopki",
						tolerancePropertySymbol: "t",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 0,
						toleranceStart: 0,
						toleranceEnd: 30,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "skośność stopek",
				propertySymbol: "k",
				propertyUnit: "mm",
				propertySecond: "skośność stopek",
				propertySecondSymbol: "k1",
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość stopki",
						rangePropertySymbol: "b",
						toleranceProperty: "skośność stopek",
						tolerancePropertySymbol: "k",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 100,
						toleranceStart: 0,
						toleranceEnd: 2,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "szerokość stopki",
						rangePropertySymbol: "b",
						toleranceProperty: "szerokość stopki",
						tolerancePropertySymbol: "b",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 100,
						rangeTo: 0,
						toleranceStart: 0,
						toleranceEnd: 2.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "wygięcie środnika",
				propertySymbol: "f",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "wygięcie środnika",
						tolerancePropertySymbol: "f",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 100,
						toleranceStart: 0.5,
						toleranceEnd: 0.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "wygięcie środnika",
						tolerancePropertySymbol: "f",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 100,
						rangeTo: 200,
						toleranceStart: 1,
						toleranceEnd: 1,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "wygięcie środnika",
						tolerancePropertySymbol: "f",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 200,
						rangeTo: 400,
						toleranceStart: 1.5,
						toleranceEnd: 1.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "wygięcie środnika",
						tolerancePropertySymbol: "f",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 400,
						rangeTo: 0,
						toleranceStart: 1.5,
						toleranceEnd: 1.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "prostość x",
				propertySymbol: "qxx",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "l",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 150,
						toleranceStart: 0.3,
						toleranceEnd: 0.3,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "l",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 150,
						rangeTo: 300,
						toleranceStart: 0.2,
						toleranceEnd: 0.2,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "l",
						toleranceUnit: "mm",
						canAgreeTolerance: false,
						rangeFrom: 300,
						rangeTo: 0,
						toleranceStart: 0.15,
						toleranceEnd: 0.15,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "prostość y",
				propertySymbol: "qyy",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "l",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 150,
						toleranceStart: 0.5,
						toleranceEnd: 0.5,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "l",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 150,
						rangeTo: 300,
						toleranceStart: 0.3,
						toleranceEnd: 0.3,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "l",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 300,
						rangeTo: 0,
						toleranceStart: 0.2,
						toleranceEnd: 0.2,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
			{
				property: "długość",
				propertySymbol: "l",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "długość",
						rangePropertySymbol: "l",
						toleranceProperty: "długość",
						tolerancePropertySymbol: "l",
						toleranceUnit: "mm",
						canAgreeTolerance: true,
						rangeFrom: 0,
						rangeTo: 0,
						toleranceStart: 0,
						toleranceEnd: 100,
						toleranceStartAgreement: 50,
						toleranceEndAgreement: 50,
					},
				],
			},
			{
				property: "masa",
				propertySymbol: "kg/m",
				propertyUnit: "mm",
				propertySecond: null,
				propertySecondSymbol: null,
				propertySecondOperation: null,
				ranges: [
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "masa",
						tolerancePropertySymbol: "kg/m",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 0,
						rangeTo: 125,
						toleranceStart: 6,
						toleranceEnd: 6,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
					{
						rangeUnit: "mm",
						rangeProperty: "wysokość",
						rangePropertySymbol: "h",
						toleranceProperty: "masa",
						tolerancePropertySymbol: "kg/m",
						toleranceUnit: "%",
						canAgreeTolerance: false,
						rangeFrom: 125,
						rangeTo: 0,
						toleranceStart: 4,
						toleranceEnd: 4,
						toleranceStartAgreement: 0,
						toleranceEndAgreement: 0,
					},
				],
			},
		],
		allNeededValues: [
			{
				name: "wysokość",
				symbol: "h",
				unit: "mm",
			},
			{
				name: "szerokość stopki",
				symbol: "b",
				unit: "mm",
			},
			{
				name: "grubość środnika",
				symbol: "s",
				unit: "mm",
			},
			{
				name: "grubość stopki",
				symbol: "t",
				unit: "mm",
			},
			{
				name: "promień naroża",
				symbol: "r3",
				unit: "mm",
			},
			{
				name: "skośność stopek",
				symbol: "k",
				unit: "mm",
			},
			{
				name: "skośność stopek",
				symbol: "k1",
				unit: "mm",
			},
			{
				name: "wygięcie środnika",
				symbol: "f",
				unit: "mm",
			},
			{
				name: "prostość x",
				symbol: "qxx",
				unit: "mm",
			},
			{
				name: "prostość y",
				symbol: "qyy",
				unit: "mm",
			},
			{
				name: "długość",
				symbol: "l",
				unit: "mm",
			},
			{
				name: "masa",
				symbol: "kg/m",
				unit: "mm",
			},
		],
	},
];

export const PNEN10024 = MockData[0];
export const PNEN100562 = MockData[1];
export const PNEN10058 = MockData[2];
export const PNEN10279 = MockData[3];
