INSERT INTO elements(
              code,
              name,
              property,
              propertySymbol,
              propertySecond,
              propertySecondSymbol,
              propertiesOperation,
              propertyUnit,
              rangeFrom,
              rangeTo,
              rangeUnit,
              rangeProperty,
              rangePropertySymbol,
              toleranceStart,
              toleranceEnd,
              toleranceUnit,
              toleranceProperty,
              tolerancePropertySymbol,
              illustration,
              toleranceStartAgreement,
              toleranceEndAgreement
       )
VALUES(
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'wysokość',
              'h',
              NULL,
              NULL,
              NULL,
              'mm',
              0,
              65,
              'mm',
              'wysokość',
              'h',
              1.5,
              1.5,
              'mm',
              'wysokość',
              'h',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'wysokość',
              'h',
              NULL,
              NULL,
              NULL,
              'mm',
              65,
              200,
              'mm',
              'wysokość',
              'h',
              2,
              2,
              'mm',
              'wysokość',
              'h',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'wysokość',
              'h',
              NULL,
              NULL,
              NULL,
              'mm',
              200,
              400,
              'mm',
              'wysokość',
              'h',
              3,
              3,
              'mm',
              'wysokość',
              'h',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'wysokość',
              'h',
              NULL,
              NULL,
              NULL,
              'mm',
              400,
              NULL,
              'mm',
              'wysokość',
              'h',
              4,
              4,
              'mm',
              'wysokość',
              'h',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'szerokość stopki',
              'b',
              NULL,
              NULL,
              NULL,
              'mm',
              0,
              50,
              'mm',
              'szerokość stopki',
              'b',
              1.5,
              1.5,
              'mm',
              'szerokość stopki',
              'b',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'szerokość stopki',
              'b',
              NULL,
              NULL,
              NULL,
              'mm',
              50,
              100,
              'mm',
              'szerokość stopki',
              'b',
              2,
              2,
              'mm',
              'szerokość stopki',
              'b',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'szerokość stopki',
              'b',
              NULL,
              NULL,
              NULL,
              'mm',
              100,
              125,
              'mm',
              'szerokość stopki',
              'b',
              2.5,
              2.5,
              'mm',
              'szerokość stopki',
              'b',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'szerokość stopki',
              'b',
              NULL,
              NULL,
              NULL,
              'mm',
              125,
              NULL,
              'mm',
              'szerokość stopki',
              'b',
              3,
              3,
              'mm',
              'szerokość stopki',
              'b',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'grubość środnika',
              's',
              NULL,
              NULL,
              NULL,
              'mm',
              0,
              10,
              'mm',
              'grubość środnika',
              's',
              0.5,
              0.5,
              'mm',
              'grubość środnika',
              's',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'grubość środnika',
              's',
              NULL,
              NULL,
              NULL,
              'mm',
              10,
              15,
              'mm',
              'grubość środnika',
              's',
              0.7,
              0.7,
              'mm',
              'grubość środnika',
              's',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'grubość środnika',
              's',
              NULL,
              NULL,
              NULL,
              'mm',
              15,
              NULL,
              'mm',
              'grubość środnika',
              's',
              1,
              1,
              'mm',
              'grubość środnika',
              's',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'grubość stopki',
              't',
              NULL,
              NULL,
              NULL,
              'mm',
              0,
              10,
              'mm',
              'grubość stopki',
              't',
              0.5,
              0,
              'mm',
              'grubość stopki',
              't',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'grubość stopki',
              't',
              NULL,
              NULL,
              NULL,
              'mm',
              10,
              15,
              'mm',
              'grubość stopki',
              't',
              1,
              0,
              'mm',
              'grubość stopki',
              't',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'grubość stopki',
              't',
              NULL,
              NULL,
              NULL,
              'mm',
              15,
              NULL,
              'mm',
              'grubość stopki',
              't',
              1.5,
              0,
              'mm',
              'grubość stopki',
              't',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'promień naroża',
              'r3',
              NULL,
              NULL,
              NULL,
              'mm',
              NULL,
              NULL,
              'mm',
              'promień naroża',
              'r3',
              0,
              30,
              '%',
              'grubość stopki',
              't',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'skośność stopek',
              'k',
              'skośność stopek',
              'k1',
              'ADDITION',
              'mm',
              0,
              100,
              'mm',
              'szerokość stopki',
              'b',
              0,
              2,
              'mm',
              'skośność stopek',
              'k',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'skośność stopek',
              'k',
              'skośność stopek',
              'k1',
              'ADDITION',
              'mm',
              100,
              NULL,
              'mm',
              'szerokość stopki',
              'b',
              0,
              2.5,
              '%',
              'szerokość stopki',
              'b',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'wygięcie środnika',
              'f',
              NULL,
              NULL,
              NULL,
              'mm',
              0,
              100,
              'mm',
              'wysokość',
              'h',
              0.5,
              0.5,
              'mm',
              'wygięcie środnika',
              'f',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'wygięcie środnika',
              'f',
              NULL,
              NULL,
              NULL,
              'mm',
              100,
              200,
              'mm',
              'wysokość',
              'h',
              1,
              1,
              'mm',
              'wygięcie środnika',
              'f',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'wygięcie środnika',
              'f',
              NULL,
              NULL,
              NULL,
              'mm',
              200,
              400,
              'mm',
              'wysokość',
              'h',
              1.5,
              1.5,
              'mm',
              'wygięcie środnika',
              'f',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'wygięcie środnika',
              'f',
              NULL,
              NULL,
              NULL,
              'mm',
              400,
              NULL,
              'mm',
              'wysokość',
              'h',
              1.5,
              1.5,
              'mm',
              'wygięcie środnika',
              'f',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'prostość x',
              'qxx',
              NULL,
              NULL,
              NULL,
              'mm',
              0,
              150,
              'mm',
              'wysokość',
              'h',
              0.3,
              0.3,
              '%',
              'długość',
              'l',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'prostość x',
              'qxx',
              NULL,
              NULL,
              NULL,
              'mm',
              150,
              300,
              'mm',
              'wysokość',
              'h',
              0.2,
              0.2,
              '%',
              'długość',
              'l',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'prostość x',
              'qxx',
              NULL,
              NULL,
              NULL,
              'mm',
              300,
              NULL,
              'mm',
              'wysokość',
              'h',
              0.15,
              0.15,
              'mm',
              'długość',
              'l',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'prostość y',
              'qyy',
              NULL,
              NULL,
              NULL,
              'mm',
              0,
              150,
              'mm',
              'wysokość',
              'h',
              0.5,
              0.5,
              '%',
              'długość',
              'l',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'prostość y',
              'qyy',
              NULL,
              NULL,
              NULL,
              'mm',
              150,
              300,
              'mm',
              'wysokość',
              'h',
              0.3,
              0.3,
              '%',
              'długość',
              'l',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'prostość y',
              'qyy',
              NULL,
              NULL,
              NULL,
              'mm',
              300,
              NULL,
              'mm',
              'wysokość',
              'h',
              0.2,
              0.2,
              '%',
              'długość',
              'l',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'długość',
              'l',
              NULL,
              NULL,
              NULL,
              'mm',
              NULL,
              NULL,
              'mm',
              'długość',
              'l',
              0,
              100,
              'mm',
              'długość',
              'l',
              NULL,
              50,
              50
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'masa',
              'kg/m',
              NULL,
              NULL,
              NULL,
              'mm',
              0,
              125,
              'mm',
              'wysokość',
              'h',
              6,
              6,
              '%',
              'masa',
              'kg/m',
              NULL,
              NULL,
              NULL
       ),
       (
              'PN-EN 10279',
              'CELOWNIKI STALOWE WALCOWANE NA GORĄCO',
              'masa',
              'kg/m',
              NULL,
              NULL,
              NULL,
              'mm',
              125,
              NULL,
              'mm',
              'wysokość',
              'h',
              4,
              4,
              '%',
              'masa',
              'kg/m',
              NULL,
              NULL,
              NULL
       )